steps:
  - name: ":node: Test"
    command: ".buildkite/test.sh"
    timeout_in_minutes: 15
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: node
    agents:
      docker: "*"

  - wait

  - command: ".buildkite/publish.sh"
    label: ":s3: Publish"
    branches: master
    agents:
      docker: "*"
